import {
  buildStandardObject,
  type StandardObjectInput,
} from 'src/standard/build';
import { type FlatObjectMetadata } from 'src/metadata/types';

const MANY_TO_ONE = {
  relationType: 'MANY_TO_ONE',
  onDelete: 'SET_NULL',
} as const;

const ONE_TO_MANY = { relationType: 'ONE_TO_MANY' } as const;

// The CRM core. Messaging, calendar, workflow and dashboard objects are
// deliberately out of the first cut.
export const STANDARD_OBJECT_INPUTS: StandardObjectInput[] = [
  {
    nameSingular: 'workspaceMember',
    namePlural: 'workspaceMembers',
    labelSingular: 'Workspace Member',
    labelPlural: 'Workspace Members',
    icon: 'IconUserCircle',
    isSystem: true,
    fields: [
      { name: 'name', label: 'Name', type: 'FULL_NAME' },
      { name: 'colorScheme', label: 'Color Scheme', type: 'TEXT' },
      { name: 'locale', label: 'Language', type: 'TEXT' },
      { name: 'avatarUrl', label: 'Avatar Url', type: 'TEXT' },
      { name: 'userEmail', label: 'User Email', type: 'TEXT' },
      { name: 'userId', label: 'User Id', type: 'UUID' },
      // Both sides of a relation must exist: the front dereferences
      // relation.targetFieldMetadata.id without a guard, so a MANY_TO_ONE
      // without its inverse crashes every page that renders the owning object.
      {
        name: 'authoredAttachments',
        label: 'Authored attachments',
        type: 'RELATION',
        settings: ONE_TO_MANY,
        relationTargetObjectNameSingular: 'attachment',
        relationTargetFieldName: 'author',
      },
      {
        name: 'timelineActivities',
        label: 'Timeline Activities',
        type: 'RELATION',
        settings: ONE_TO_MANY,
        relationTargetObjectNameSingular: 'timelineActivity',
        relationTargetFieldName: 'workspaceMember',
      },
      {
        name: 'assignedTasks',
        label: 'Assigned tasks',
        type: 'RELATION',
        settings: ONE_TO_MANY,
        relationTargetObjectNameSingular: 'task',
        relationTargetFieldName: 'assignee',
      },
    ],
  },
  {
    nameSingular: 'company',
    namePlural: 'companies',
    labelSingular: 'Company',
    labelPlural: 'Companies',
    icon: 'IconBuildingSkyscraper',
    duplicateCriteria: [['name'], ['domainNamePrimaryLinkUrl']],
    fields: [
      { name: 'name', label: 'Name', type: 'TEXT' },
      { name: 'domainName', label: 'Domain Name', type: 'LINKS' },
      { name: 'address', label: 'Address', type: 'ADDRESS' },
      { name: 'employees', label: 'Employees', type: 'NUMBER' },
      { name: 'linkedinLink', label: 'Linkedin', type: 'LINKS' },
      { name: 'annualRecurringRevenue', label: 'ARR', type: 'CURRENCY' },
      { name: 'idealCustomerProfile', label: 'ICP', type: 'BOOLEAN' },
      {
        name: 'people',
        label: 'People',
        type: 'RELATION',
        settings: ONE_TO_MANY,
        relationTargetObjectNameSingular: 'person',
        relationTargetFieldName: 'company',
      },
      {
        name: 'opportunities',
        label: 'Opportunities',
        type: 'RELATION',
        settings: ONE_TO_MANY,
        relationTargetObjectNameSingular: 'opportunity',
        relationTargetFieldName: 'company',
      },
      {
        name: 'noteTargets',
        label: 'Notes',
        type: 'RELATION',
        settings: ONE_TO_MANY,
        relationTargetObjectNameSingular: 'noteTarget',
        relationTargetFieldName: 'target',
      },
      {
        name: 'taskTargets',
        label: 'Tasks',
        type: 'RELATION',
        settings: ONE_TO_MANY,
        relationTargetObjectNameSingular: 'taskTarget',
        relationTargetFieldName: 'target',
      },
      {
        name: 'attachments',
        label: 'Attachments',
        type: 'RELATION',
        settings: ONE_TO_MANY,
        relationTargetObjectNameSingular: 'attachment',
        relationTargetFieldName: 'target',
      },
      {
        name: 'timelineActivities',
        label: 'Timeline Activities',
        type: 'RELATION',
        settings: ONE_TO_MANY,
        relationTargetObjectNameSingular: 'timelineActivity',
        relationTargetFieldName: 'target',
      },
    ],
  },
  {
    nameSingular: 'person',
    namePlural: 'people',
    labelSingular: 'Person',
    labelPlural: 'People',
    icon: 'IconUser',
    duplicateCriteria: [
      ['nameFirstName', 'nameLastName'],
      ['linkedinLinkPrimaryLinkUrl'],
      ['emailsPrimaryEmail'],
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'FULL_NAME' },
      { name: 'emails', label: 'Emails', type: 'EMAILS' },
      { name: 'phones', label: 'Phones', type: 'PHONES' },
      { name: 'jobTitle', label: 'Job Title', type: 'TEXT' },
      { name: 'city', label: 'City', type: 'TEXT' },
      { name: 'avatarUrl', label: 'Avatar', type: 'TEXT' },
      { name: 'linkedinLink', label: 'Linkedin', type: 'LINKS' },
      {
        name: 'company',
        label: 'Company',
        type: 'RELATION',
        settings: MANY_TO_ONE,
        relationTargetObjectNameSingular: 'company',
        relationTargetFieldName: 'people',
      },
      {
        name: 'noteTargets',
        label: 'Notes',
        type: 'RELATION',
        settings: ONE_TO_MANY,
        relationTargetObjectNameSingular: 'noteTarget',
        relationTargetFieldName: 'target',
      },
      {
        name: 'taskTargets',
        label: 'Tasks',
        type: 'RELATION',
        settings: ONE_TO_MANY,
        relationTargetObjectNameSingular: 'taskTarget',
        relationTargetFieldName: 'target',
      },
      {
        name: 'attachments',
        label: 'Attachments',
        type: 'RELATION',
        settings: ONE_TO_MANY,
        relationTargetObjectNameSingular: 'attachment',
        relationTargetFieldName: 'target',
      },
      {
        name: 'timelineActivities',
        label: 'Timeline Activities',
        type: 'RELATION',
        settings: ONE_TO_MANY,
        relationTargetObjectNameSingular: 'timelineActivity',
        relationTargetFieldName: 'target',
      },
    ],
  },
  {
    nameSingular: 'opportunity',
    namePlural: 'opportunities',
    labelSingular: 'Opportunity',
    labelPlural: 'Opportunities',
    icon: 'IconTargetArrow',
    fields: [
      { name: 'name', label: 'Name', type: 'TEXT' },
      { name: 'amount', label: 'Amount', type: 'CURRENCY' },
      { name: 'closeDate', label: 'Close date', type: 'DATE_TIME' },
      {
        name: 'stage',
        label: 'Stage',
        type: 'SELECT',
        defaultValue: 'NEW',
        options: [
          { value: 'NEW', label: 'New', color: 'red', position: 0 },
          { value: 'SCREENING', label: 'Screening', color: 'purple', position: 1 },
          { value: 'MEETING', label: 'Meeting', color: 'sky', position: 2 },
          { value: 'PROPOSAL', label: 'Proposal', color: 'turquoise', position: 3 },
          { value: 'CUSTOMER', label: 'Customer', color: 'yellow', position: 4 },
        ],
      },
      {
        name: 'company',
        label: 'Company',
        type: 'RELATION',
        settings: MANY_TO_ONE,
        relationTargetObjectNameSingular: 'company',
        relationTargetFieldName: 'opportunities',
      },
      {
        name: 'noteTargets',
        label: 'Notes',
        type: 'RELATION',
        settings: ONE_TO_MANY,
        relationTargetObjectNameSingular: 'noteTarget',
        relationTargetFieldName: 'target',
      },
      {
        name: 'taskTargets',
        label: 'Tasks',
        type: 'RELATION',
        settings: ONE_TO_MANY,
        relationTargetObjectNameSingular: 'taskTarget',
        relationTargetFieldName: 'target',
      },
      {
        name: 'attachments',
        label: 'Attachments',
        type: 'RELATION',
        settings: ONE_TO_MANY,
        relationTargetObjectNameSingular: 'attachment',
        relationTargetFieldName: 'target',
      },
      {
        name: 'timelineActivities',
        label: 'Timeline Activities',
        type: 'RELATION',
        settings: ONE_TO_MANY,
        relationTargetObjectNameSingular: 'timelineActivity',
        relationTargetFieldName: 'target',
      },
    ],
  },
  {
    nameSingular: 'note',
    namePlural: 'notes',
    labelSingular: 'Note',
    labelPlural: 'Notes',
    icon: 'IconNotes',
    labelIdentifierFieldName: 'title',
    fields: [
      { name: 'title', label: 'Title', type: 'TEXT' },
      { name: 'body', label: 'Body', type: 'RICH_TEXT' },
      {
        name: 'noteTargets',
        label: 'Relations',
        type: 'RELATION',
        settings: ONE_TO_MANY,
        relationTargetObjectNameSingular: 'noteTarget',
        relationTargetFieldName: 'note',
      },
      {
        name: 'attachments',
        label: 'Attachments',
        type: 'RELATION',
        settings: ONE_TO_MANY,
        relationTargetObjectNameSingular: 'attachment',
        relationTargetFieldName: 'target',
      },
      {
        name: 'timelineActivities',
        label: 'Timeline Activities',
        type: 'RELATION',
        settings: ONE_TO_MANY,
        relationTargetObjectNameSingular: 'timelineActivity',
        relationTargetFieldName: 'target',
      },
    ],
  },
  {
    nameSingular: 'task',
    namePlural: 'tasks',
    labelSingular: 'Task',
    labelPlural: 'Tasks',
    icon: 'IconCheckbox',
    labelIdentifierFieldName: 'title',
    fields: [
      { name: 'title', label: 'Title', type: 'TEXT' },
      { name: 'body', label: 'Body', type: 'RICH_TEXT' },
      { name: 'dueAt', label: 'Due Date', type: 'DATE_TIME' },
      {
        name: 'status',
        label: 'Status',
        type: 'SELECT',
        defaultValue: 'TODO',
        options: [
          { value: 'TODO', label: 'To do', color: 'sky', position: 0 },
          { value: 'IN_PROGRESS', label: 'In progress', color: 'purple', position: 1 },
          { value: 'DONE', label: 'Done', color: 'green', position: 2 },
        ],
      },
      {
        name: 'assignee',
        label: 'Assignee',
        type: 'RELATION',
        settings: MANY_TO_ONE,
        relationTargetObjectNameSingular: 'workspaceMember',
        relationTargetFieldName: 'assignedTasks',
      },
      {
        name: 'taskTargets',
        label: 'Relations',
        type: 'RELATION',
        settings: ONE_TO_MANY,
        relationTargetObjectNameSingular: 'taskTarget',
        relationTargetFieldName: 'task',
      },
      {
        name: 'attachments',
        label: 'Attachments',
        type: 'RELATION',
        settings: ONE_TO_MANY,
        relationTargetObjectNameSingular: 'attachment',
        relationTargetFieldName: 'target',
      },
      {
        name: 'timelineActivities',
        label: 'Timeline Activities',
        type: 'RELATION',
        settings: ONE_TO_MANY,
        relationTargetObjectNameSingular: 'timelineActivity',
        relationTargetFieldName: 'target',
      },
    ],
  },
  {
    nameSingular: 'attachment',
    namePlural: 'attachments',
    labelSingular: 'Attachment',
    labelPlural: 'Attachments',
    icon: 'IconFileImport',
    fields: [
      { name: 'name', label: 'Name', type: 'TEXT' },
      // fullPath and type are the deprecated pair the front still reads; the
      // upload path writes `file` instead, and refuses to start at all when the
      // attachment object has no FILES field to name in createFileUpload.
      { name: 'fullPath', label: 'Full path', type: 'TEXT' },
      { name: 'type', label: 'Type', type: 'TEXT' },
      { name: 'file', label: 'File', type: 'FILES' },
      {
        name: 'author',
        label: 'Author',
        type: 'RELATION',
        settings: MANY_TO_ONE,
        relationTargetObjectNameSingular: 'workspaceMember',
        relationTargetFieldName: 'authoredAttachments',
      },
      {
        name: 'target',
        label: 'Target',
        type: 'MORPH_RELATION',
        settings: MANY_TO_ONE,
        morphTargets: [
          { nameSingular: 'company', namePlural: 'companies', fieldName: 'attachments' },
          { nameSingular: 'person', namePlural: 'people', fieldName: 'attachments' },
          { nameSingular: 'opportunity', namePlural: 'opportunities', fieldName: 'attachments' },
          { nameSingular: 'note', namePlural: 'notes', fieldName: 'attachments' },
          { nameSingular: 'task', namePlural: 'tasks', fieldName: 'attachments' },
        ],
      },
    ],
  },
  // Twenty links a note or a task to several records through a junction object
  // rather than a column per target, which is what lets one note belong to a
  // company and a person at once. Both are system objects: they exist for the
  // Notes and Tasks tabs, not for the sidebar.
  {
    nameSingular: 'noteTarget',
    namePlural: 'noteTargets',
    labelSingular: 'Note Target',
    labelPlural: 'Note Targets',
    icon: 'IconCheckbox',
    isSystem: true,
    fields: [
      {
        name: 'note',
        label: 'Note',
        type: 'RELATION',
        settings: MANY_TO_ONE,
        relationTargetObjectNameSingular: 'note',
        relationTargetFieldName: 'noteTargets',
      },
      {
        name: 'target',
        label: 'Target',
        type: 'MORPH_RELATION',
        settings: MANY_TO_ONE,
        morphTargets: [
          { nameSingular: 'company', namePlural: 'companies', fieldName: 'noteTargets' },
          { nameSingular: 'person', namePlural: 'people', fieldName: 'noteTargets' },
          { nameSingular: 'opportunity', namePlural: 'opportunities', fieldName: 'noteTargets' },
        ],
      },
    ],
  },
  {
    nameSingular: 'taskTarget',
    namePlural: 'taskTargets',
    labelSingular: 'Task Target',
    labelPlural: 'Task Targets',
    icon: 'IconCheckbox',
    isSystem: true,
    fields: [
      {
        name: 'task',
        label: 'Task',
        type: 'RELATION',
        settings: MANY_TO_ONE,
        relationTargetObjectNameSingular: 'task',
        relationTargetFieldName: 'taskTargets',
      },
      {
        name: 'target',
        label: 'Target',
        type: 'MORPH_RELATION',
        settings: MANY_TO_ONE,
        morphTargets: [
          { nameSingular: 'company', namePlural: 'companies', fieldName: 'taskTargets' },
          { nameSingular: 'person', namePlural: 'people', fieldName: 'taskTargets' },
          { nameSingular: 'opportunity', namePlural: 'opportunities', fieldName: 'taskTargets' },
        ],
      },
    ],
  },
  {
    nameSingular: 'timelineActivity',
    namePlural: 'timelineActivities',
    labelSingular: 'Timeline Activity',
    labelPlural: 'Timeline Activities',
    icon: 'IconTimelineEvent',
    isSystem: true,
    labelIdentifierFieldName: 'name',
    fields: [
      { name: 'name', label: 'Event name', type: 'TEXT' },
      { name: 'properties', label: 'Event details', type: 'RAW_JSON' },
      { name: 'happensAt', label: 'Creation date', type: 'DATE_TIME', defaultValue: 'now' },
      { name: 'linkedRecordId', label: 'Linked Record id', type: 'UUID' },
      { name: 'linkedRecordCachedName', label: 'Linked Record cached name', type: 'TEXT' },
      { name: 'linkedObjectMetadataId', label: 'Linked Object Metadata Id', type: 'UUID' },
      { name: 'timelineActivityTypeId', label: 'Timeline Activity Type Id', type: 'UUID' },
      // The snapshot is what renders a past event whose type was since renamed
      // or deleted; the live type only overrides its labels when it still exists.
      { name: 'timelineActivityTypeSnapshot', label: 'Timeline Activity Type Snapshot', type: 'RAW_JSON' },
      {
        name: 'workspaceMember',
        label: 'Workspace Member',
        type: 'RELATION',
        settings: MANY_TO_ONE,
        relationTargetObjectNameSingular: 'workspaceMember',
        relationTargetFieldName: 'timelineActivities',
      },
      {
        name: 'target',
        label: 'Target',
        type: 'MORPH_RELATION',
        settings: MANY_TO_ONE,
        morphTargets: [
          { nameSingular: 'company', namePlural: 'companies', fieldName: 'timelineActivities' },
          { nameSingular: 'person', namePlural: 'people', fieldName: 'timelineActivities' },
          { nameSingular: 'opportunity', namePlural: 'opportunities', fieldName: 'timelineActivities' },
          { nameSingular: 'note', namePlural: 'notes', fieldName: 'timelineActivities' },
          { nameSingular: 'task', namePlural: 'tasks', fieldName: 'timelineActivities' },
        ],
      },
    ],
  },
];

export const buildStandardObjects = (
  workspaceId: string,
): FlatObjectMetadata[] =>
  STANDARD_OBJECT_INPUTS.map((input) =>
    buildStandardObject({ input, workspaceId }),
  );
