import { defineObject, FieldType } from 'twenty-sdk/define';

import { GATEWAY_CONTRACT } from 'src/twenty/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: GATEWAY_CONTRACT.object,
  nameSingular: 'gatewayContract',
  namePlural: 'gatewayContracts',
  labelSingular: 'Contrato',
  labelPlural: 'Contratos',
  description:
    'Um contrato do gateway vinculado a um Clube ou a um Membro. Os campos sao "external" porque valem para qualquer gateway, nao so a Routerfy.',
  icon: 'IconFileDollar',
  labelIdentifierFieldMetadataUniversalIdentifier: GATEWAY_CONTRACT.name,
  fields: [
    {
      universalIdentifier: GATEWAY_CONTRACT.name,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Numero',
      description: 'O numero do contrato como aparece no painel do gateway',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: GATEWAY_CONTRACT.externalSubscriptionId,
      type: FieldType.TEXT,
      name: 'externalSubscriptionId',
      label: 'Id da assinatura',
      icon: 'IconRepeat',
      isNullable: true,
    },
    {
      universalIdentifier: GATEWAY_CONTRACT.externalTransactionId,
      type: FieldType.TEXT,
      name: 'externalTransactionId',
      label: 'Id da transacao',
      icon: 'IconReceipt',
      isNullable: true,
    },
    {
      universalIdentifier: GATEWAY_CONTRACT.contractKind,
      type: FieldType.SELECT,
      name: 'contractKind',
      label: 'Tipo',
      icon: 'IconCategory',
      defaultValue: "'SUBSCRIPTION'",
      options: [
        {
          id: '9378fc91-1af2-4e90-8261-4eb69c2d9bc9',
          value: 'SUBSCRIPTION',
          label: 'Recorrencia',
          position: 0,
          color: 'blue',
        },
        {
          id: 'e93756e3-1692-431e-acb6-a5505e137cf4',
          value: 'TRANSACTION',
          label: 'A vista',
          position: 1,
          color: 'purple',
        },
      ],
    },
    {
      universalIdentifier: GATEWAY_CONTRACT.contractStatus,
      type: FieldType.TEXT,
      name: 'contractStatus',
      label: 'Situacao',
      description:
        'Como o gateway chama a situacao. E texto porque cada gateway tem o seu vocabulario, e traduzir aqui perderia o original.',
      icon: 'IconProgress',
      isNullable: true,
    },
    {
      universalIdentifier: GATEWAY_CONTRACT.amount,
      type: FieldType.CURRENCY,
      name: 'amount',
      label: 'Valor da parcela',
      icon: 'IconCurrencyReal',
      isNullable: true,
    },
    {
      universalIdentifier: GATEWAY_CONTRACT.totalValue,
      type: FieldType.CURRENCY,
      name: 'totalValue',
      label: 'Valor total',
      description:
        'Soma das faturas, que e onde desconto e acrescimo aparecem. Sem faturas, cai no valor da parcela.',
      icon: 'IconSum',
      isNullable: true,
    },
    {
      universalIdentifier: GATEWAY_CONTRACT.frequency,
      type: FieldType.SELECT,
      name: 'frequency',
      label: 'Periodicidade',
      icon: 'IconCalendarRepeat',
      isNullable: true,
      options: [
        {
          id: '8dfd31be-ecdf-48e0-b2d7-0476de10af64',
          value: 'day',
          label: 'Dia',
          position: 0,
          color: 'gray',
        },
        {
          id: '5bad6da6-ad13-4f38-a7c8-298f42fd509c',
          value: 'week',
          label: 'Semana',
          position: 1,
          color: 'gray',
        },
        {
          id: '9d4d990e-5af6-4931-9d79-bbc53fd094a6',
          value: 'month',
          label: 'Mes',
          position: 2,
          color: 'blue',
        },
        {
          id: '11931705-7c2a-4df2-8b90-c9d7b21e15fa',
          value: 'year',
          label: 'Ano',
          position: 3,
          color: 'green',
        },
      ],
    },
    {
      universalIdentifier: GATEWAY_CONTRACT.frequencyInterval,
      type: FieldType.NUMBER,
      name: 'frequencyInterval',
      label: 'A cada',
      icon: 'IconNumbers',
      isNullable: true,
    },
    {
      universalIdentifier: GATEWAY_CONTRACT.startsAt,
      type: FieldType.DATE_TIME,
      name: 'startsAt',
      label: 'Inicio',
      icon: 'IconCalendarPlus',
      isNullable: true,
    },
    {
      universalIdentifier: GATEWAY_CONTRACT.endsAt,
      type: FieldType.DATE_TIME,
      name: 'endsAt',
      label: 'Termino',
      icon: 'IconCalendarMinus',
      isNullable: true,
    },
    {
      universalIdentifier: GATEWAY_CONTRACT.nextChargeAt,
      type: FieldType.DATE_TIME,
      name: 'nextChargeAt',
      label: 'Proxima cobranca',
      icon: 'IconCalendarClock',
      isNullable: true,
    },
    {
      universalIdentifier: GATEWAY_CONTRACT.paidInvoicesCount,
      type: FieldType.NUMBER,
      name: 'paidInvoicesCount',
      label: 'Parcelas pagas',
      icon: 'IconChecks',
      isNullable: true,
    },
    {
      universalIdentifier: GATEWAY_CONTRACT.paymentMethod,
      type: FieldType.TEXT,
      name: 'paymentMethod',
      label: 'Forma de pagamento',
      icon: 'IconCreditCard',
      isNullable: true,
    },
    {
      universalIdentifier: GATEWAY_CONTRACT.customerEmail,
      type: FieldType.TEXT,
      name: 'customerEmail',
      label: 'E-mail no gateway',
      description:
        'O e-mail do cliente no gateway no momento do vinculo. Fica gravado para auditar por que este contrato foi aceito aqui.',
      icon: 'IconMail',
      isNullable: true,
    },
    {
      universalIdentifier: GATEWAY_CONTRACT.customerDocument,
      type: FieldType.TEXT,
      name: 'customerDocument',
      label: 'Documento no gateway',
      icon: 'IconId',
      isNullable: true,
    },
  ],
});
